version: '2'
services:
  nginx:
   container_name: some-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
  backend:
    restart: always
    build: ./backend
    working_dir: /backend
    volumes:
      - ./backend:/backend
    expose:
      - "8080"
    command: mvn clean spring-boot:run
    depends_on:
      - nginx